#!/usr/bin/env ruby

require "thor"
require_relative "../lib/rpw"

module RPW
  class CLI < Thor
    class_option :verbose, type: :boolean, aliases: "-v"

    desc "next", "Proceed to the next section of the workshop"

    def next
      client.next
    end

    desc "setup", "Set up your purchase key in order to download workshop sections"

    def setup
      say "We'll create a .rpw_key file in the current directory to save your key for future use."
      key = ask("Purchase Key: ")

      client.setup(key)

      say "Successfully authenticated with the RPW server and saved your key."
    end

    desc "status", "Show your current workshop progression"

    def status
      # ...
    end

    desc "support", "Create a new support ticket, report a bug or issue"

    def support
    end

    desc "show CONTENT", "Show any workshop section (use list to see all section names)"

    def show(content)
    end

    desc "list", "Show all available workshop content"

    def list
    end

    desc "download [CONTENT | all]", "Download one or all workshop contents"

    def download(content)
    end

    private

    def client
      @client ||= RPW::Client.new
    end
  end
end

RPW::CLI.start(ARGV)
