#!/usr/bin/env ruby

require "thor"
require "thor/hollaback"
require_relative "../lib/rpw"

module RPW
  class SubCommandBase < Thor
    def self.banner(command, namespace = nil, subcommand = false)
      "#{basename} #{subcommand_prefix} #{command.usage}"
    end

    def self.subcommand_prefix
      name.gsub(%r{.*::}, "").gsub(%r{^[A-Z]}) { |match| match[0].downcase }.gsub(%r{[A-Z]}) { |match| "-#{match[0].downcase}" }
    end

    no_commands do
      def client
        @client ||= RPW::Client.new
      end
    end
  end

  class Key < SubCommandBase
    desc "register [EMAIL_ADDRESS]", "Change email registered with Speedshop. One-time only."
    def register(email)
      client.register_email(email)
      say "License registered. You should receive a Slack invite soon."
    end
  end

  class Lesson < SubCommandBase
    class_before :exit_with_no_key

    desc "next", "Proceed to the next lesson of the workshop"
    option :open
    def next
      say "Proceeding to next lesson..."
      client.next(options[:open])
    end

    desc "complete", "Mark the current lesson as complete"

    def complete
      say "Marked current lesson as complete"
      client.complete
    end

    desc "list", "Show all available workshop lessons"

    def list
      say "All available workshop lessons:"
      client.list.each do |lesson|
        puts "#{"  " * lesson["indent"]}[#{lesson["position"]}]: #{lesson["title"]}"
      end
    end

    desc "download [CONTENT | all]", "Download one or all workshop contents"

    def download(content)
      client.download(content)
    end

    desc "show [CONTENT]", "Show any workshop lesson, shows current lesson w/no arguments"
    option :open
    def show(content = :current)
      client.show(content, options[:open])
    end

    private

    def exit_with_no_key
      exit(1) unless client.setup?
    end
  end

  class Progress < SubCommandBase
    class_before :exit_with_no_key

    desc "set [LESSON]", "Set current lesson to a particular lesson"

    def set(lesson)
      client.set_progress(lesson)
    end

    desc "reset", "Erase all progress and start over"

    def reset
      yes? "Are you sure you want to reset your progress? (Y/N)"
      client.reset_progress
    end

    desc "show", "Show current workshop progress"
    def show
      data = client.progress
      say "The Rails Performance Workshop"
      say "You have completed #{data[:completed]} out of #{data[:total]} total sections."
      say "Current lesson: #{data[:current_lesson]["title"]}"
      say "Progress by Section (X == completed, O == current):"
      data[:sections].each do |section|
        say "#{section[:title]}: #{section[:progress]}"
      end
    end

    private

    def exit_with_no_key
      exit(1) unless client.setup?
    end

    default_task :show
  end

  class CLI < Thor
    class_before :check_version
    class_before :check_setup

    desc "key register [EMAIL_ADDRESS]", "Change email registered w/Speedshop"
    subcommand "key", Key
    desc "lesson [SUBCOMMAND]", "View and download lessons"
    subcommand "lesson", Lesson
    desc "progress [SUBCOMMAND]", "View and set progress"
    subcommand "progress", Progress

    def self.exit_on_failure?
      true
    end

    desc "start", "Tutorial and onboarding"

    def start
      warn_if_already_started

      print_banner
      say "Welcome to the Rails Performance Workshop."
      say ""
      say "This is rpw, the command line client for this workshop."
      say ""
      say "This client will download files from the internet into the current"
      say "working directory, so it's best to run this client from a new directory"
      say "that you'll use as your 'scratch space' for working on the Workshop."
      say ""
      return unless yes? "Are you in a directory that we can safely add new folders and files to? (y/N)"
      puts ""
      say "We'll also create a .rpw_info file at #{File.expand_path("~/.rpw")} to save your purchase key."
      home_dir_ok = yes?("Is this OK? (y/N) (N will create it in the current directory)")

      key = ask("Your Purchase Key: ")

      client.setup(key)

      puts ""

      say "Successfully authenticated with the RPW server and saved your key."

      puts ""

      client.directory_setup

      say "Setup complete!"
      puts ""
      say "To learn how to use this command-line client, consult README.md."
      say "Remember to ask on Slack for help if you get stuck or encounter bugs."
      say "Once you're ready to get going: $ rpw lesson next"
    end

    no_commands do
      def print_banner
        puts r
        if `tput cols 80`.to_i < 80
          puts small_banner
        else
          puts banner
        end
        puts reset
      end
    end

    private

    def client
      @client ||= RPW::Client.new
    end

    def warn_if_already_started
      return unless client.setup?
      exit(0) unless yes? "You have already started the workshop. Continuing this command will wipe all of your current progress. Continue? (y/N)"
    end

    def check_version
      unless client.latest_version?
        say "#{r}WARNING: You are running an old version of rpw."
        say "WARNING: Please run `$ gem install rpw`#{reset}"
      end
    end

    def check_setup
      unless client.setup? || current_command_chain == [:start]
        say "#{r}WARNING: You do not have a purchase key set. Run `$ rpw start`#{reset}"
      end
    end

    def r
      "\e[31m"
    end

    def reset
      "\e[0m"
    end

    def small_banner
      %(
   _____ _          _____     _ _
  |_   _| |_ ___   | __  |___|_| |___
    | | |   | -_|  |    -| .'| | |_ -|
    |_| |_|_|___|  |__|__|__,|_|_|___|
   _____         ___
  |  _  |___ ___|  _|___ ___ _____ ___ ___ ___ ___
  |   __| -_|  _|  _| . |  _|     | .'|   |  _| -_|
  |__|  |___|_| |_| |___|_| |_|_|_|__,|_|_|___|___|
   _ _ _         _       _
  | | | |___ ___| |_ ___| |_ ___ ___
  | | | | . |  _| '_|_ -|   | . | . |
  |_____|___|_| |_,_|___|_|_|___|  _|
                                |_|
        #{reset})
    end

    def banner
      %(
                                _____ _          _____     _ _
     +hmNMMMMMm/`  -ymMMNh/    |_   _| |_ ___   | __  |___|_| |___
     sMMMMMMMMMy   +MMMMMMMMy    | | |   | -_|  |    -| .'| | |_ -|
     yMMMMMMMMMMy` yMMMMMMMMN    |_| |_|_|___|  |__|__|__,|_|_|___|
     `dMMMMMMMMMMm:-dMMMMMMm:   _____         ___
      `sNMMMMMMMMMMs.:+sso:`   |  _  |___ ___|  _|___ ___ _____ ___ ___ ___ ___
        :dMMMMMMMMMMm/         |   __| -_|  _|  _| . |  _|     | .'|   |  _| -_|
   `:oss+:.sNMMMMMMMMMMy`      |__|  |___|_| |_| |___|_| |_|_|_|__,|_|_|___|___|
   /mMMMMMMd-:mMMMMMMMMMMd.     _ _ _         _       _
   NMMMMMMMMy `hMMMMMMMMMMh    | | | |___ ___| |_ ___| |_ ___ ___
   yMMMMMMMM+  `dMMMMMMMMMy    | | | | . |  _| '_|_ -|   | . | . |
   /hNMMmy-  `/mMMMMMNmy/      |_____|___|_| |_,_|___|_|_|___|  _|
                                                             |_|
        #{reset})
    end
  end
end

RPW::CLI.start(ARGV)
