name: Test

on: [push, pull_request]

jobs:
  build:
    name: >-
      ${{ matrix.os }} ${{ matrix.ruby }}
    env:
      CI: true
      TESTOPTS: -v

    runs-on: ${{ matrix.os }}
    if: |
      !(   contains(github.event.pull_request.title,  '[ci skip]')
        || contains(github.event.pull_request.title,  '[skip ci]')
        || contains(github.event.head_commit.message, '[ci skip]')
        || contains(github.event.head_commit.message, '[skip ci]'))
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-20.04, macos-10.15, windows-2019 ]
        ruby: [ 2.6, 2.7, head ]

    steps:
      - name: repo checkout
        uses: actions/checkout@v2
      
      - uses: actions/checkout@master
        with:
          repository: speedshop/licensor
          path: server 

      - name: load ruby
        uses: MSP-Greg/setup-ruby-pkgs@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: bundle install
        run:   |
          bundle install --jobs 4 --retry 3

      - name: standardrb 
        run: bundle exec standardrb 

      - name: test
        run: bundle exec rake test
